forge "http://forge.puppetlabs.com"

# Contrib.
mod 'puppetlabs/apache', :git => 'git://github.com/puppetlabs/puppetlabs-apache.git', :ref => 'd051887078363bb01a060f9c405f2875315d345c'
mod 'example42/yum',     :git => 'git://github.com/example42/puppet-yum.git',         :ref => 'v2.1.17'
mod 'puppetlabs/stdlib', :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git', :ref => '4.3.2'
