forge "http://forge.puppetlabs.com"

# Contrib.
mod 'puppetlabs/apt',       :git => 'git://github.com/puppetlabs/puppetlabs-apt.git',    :ref => '1.4.0'
mod 'puppetlabs/stdlib',    :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git', :ref => '4.1.0'
mod 'puppetlabs/apache',    :git => 'git://github.com/puppetlabs/puppetlabs-apache.git', :ref => '1.1.1'
mod 'treehouseagency/pear', :git => 'git://github.com/treehouseagency/puppet-pear.git'