jenkins:
  host:  'dispatcher.dev.drupalci.org'
  token: 'rNHMBIqAObUv2JuF0rPZ'
  job:   'test'
#log-file: '/path/to/file.log'
log-file: '../../logs/app.log'
salt: 'my-salt'
users:
  user1: 'password1'
  user2: 'password2'